[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/get_tweets"
  to = "/.netlify/functions/twitter"
  status = 200
  force = true
